AUTOCORRECT_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM = no
DYNAMIC_MACRO_ENABLE = yes
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

# Bootloader selection
BOOTLOADER = atmel-dfu
